### ISSUE TITLE
Pass ALB Target Groups to Fargate

### ISSUE THREAD

**Issue by joshgubler** [byu-oit/terraform-aws-fargate#3]
https://github.com/byu-oit/terraform-aws-fargate/blob/fc1554a703e4e0bf86608b36bd42be672b258a17/examples/example.tf#L25

Why the for loop? Why can't you just pass the ALB Target Groups directly to Fargate?

**Comment by yoshutch** [comment]
Defining the list of objects you can pass in adds that extra layer of abstraction, an interface/contract if you will, that can protect the module from changes to the underlying provider modules. But honestly I only built it that way because I didn't know you could pass in the actual objects. We can add this if it's clearer to the consumer to add the objects themselves.
